version: '3.9'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.6
    restart: always
    env_file: env/db.env
    networks:
      - moneytalk_network
    ports: 
      - 3306:3306
    volumes: 
      - DB_data:/var/lib/mariadb
  symfony:
    container_name: symfony_core
    image: bitnami/symfony:6.3
    env_file: env/symfony.env
    ports:
      - 8000:8000
    volumes: 
      - '../MoneyTalk-back-symfony/app:/app'
    networks:
      - moneytalk_network
    depends_on: 
      - mariadb
  nginx:
    image: nginx:stable
    ports:
      - '80:80'
    restart: unless-stopped
  reactjs:
    build:
      context: ../MoneyTalk-front-reactJS
      dockerfile: Dockerfile
      target: dev
    volumes:
      - '../MoneyTalk-project/MoneyTalk-front-reactJS:/usr/src/app:rw'
    ports:
      - '3000:3000'
    restart: unless-stopped

volumes:
  DB_data:
networks:
  moneytalk_network:
